name: Terraform Cloud Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
    branches:
      - main
      - dev
      - stage

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Set Terraform Cloud Token
        env:
          TFC_TOKEN: ${{ secrets.TF_API_TOKEN }} # Використовуємо токен з GitHub Secrets
        run: echo "Terraform Cloud Token set"

      # Крок 1: Ініціалізація Terraform
      - name: Terraform Init
        env:
          TF_WORKSPACE: ${{ github.ref_name }}
          TFC_TOKEN: ${{ secrets.TF_API_TOKEN }} # Передаємо токен для Terraform Cloud
        run: terraform -chdir=infra init

      # Крок 2: Перемикання на відповідний робочий простір в Terraform Cloud
      - name: Select Workspace
        env:
          TFC_TOKEN: ${{ secrets.TF_API_TOKEN }} # Передаємо токен для Terraform Cloud
        run: terraform -chdir=infra workspace select ${{ github.ref_name }}

      # Крок 3: Планування Terraform
      - name: Terraform Plan
        env:
          TFC_TOKEN: ${{ secrets.TF_API_TOKEN }} # Передаємо токен для Terraform Cloud
        run: terraform -chdir=infra plan -out=tfplan

      # Крок 4: Застосування Terraform Plan
      - name: Terraform Apply
        if: success() && (github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'stage')
        env:
          TFC_TOKEN: ${{ secrets.TF_API_TOKEN }} # Передаємо токен для Terraform Cloud
        run: terraform -chdir=infra apply -auto-approve tfplan
