name: Terraform Cloud Deployment


on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
    branches:
      - main
      - dev
      - stage

jobs:
  terraform:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set AWS credentials
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            terraform -chdir=infra init
            terraform -chdir=infra plan